### ISSUE TITLE
Move this repo to https://github.com/ev3dev/

### ISSUE THREAD

**Issue by dwalton76** [ddemidov/ev3dev-lang-fake-sys#10]
We should move it there to be with all of the other official repos for ev3dev

**Comment by ddemidov** [comment]
@dlech, I tried to do this, but got "You don’t have the permission to create repositories on ev3dev" error.

**Comment by dlech** [comment]
OK. If you transfer the repo to @dlech, then I can transfer it to ev3dev.

**Comment by ddemidov** [comment]
"dlech/ev3dev-lang-fake-sys already exists"

**Comment by dlech** [comment]
I've delete my fork, so you can try again.

**Comment by ddemidov** [comment]
Done.

**Comment by dlech** [comment]
And done. Anyone that can write to ev3dev/ev3dev-lang should be able to write to this repository now.
