### ISSUE TITLE
Add a way to set properties on devices

### ISSUE THREAD

**Issue by WasabiFan** [ddemidov/ev3dev-lang-fake-sys#3]
Now that we can put the devices where we need them and clean at will, we should figure out how we want to handle testing reading of properties while changing the values. Do we want to have the `populate_arena` script accept keys and values? This could get complicated and unwieldy; I think instead we should have the populate script print to stdout an EOL-separated list of the paths to the devices that it creates. Then the consumer tests can both set values and read values manually (and be assured that they are reading from the right place).

If this is what we decide we want to do, I can open a PR.

**Comment by ddemidov** [comment]
I am not sure I understand. The testing in [python](https://github.com/rhempel/ev3dev-lang-python/blob/master/tests/api_tests.py#L8) and [C++](https://github.com/ddemidov/ev3dev-lang-cpp/blob/master/tests/CMakeLists.txt#L1) is currently done by replacing the path to `/sys/class` with the path to the test arena. Then normal API is used to connect the devices and read the attributes. Why would you need paths to the created devices?

**Comment by WasabiFan** [comment]
Let's say I want to test that my file handle caching is not actually just caching the value read from the file the first time. Currently, to test this, I would need to `populate_arena`, then construct the path to the device(s) that I just created by concatenating the root dir, the type of device, and the device index that I passed it, then open one of the property files in that folder and change the value.

I am proposing that we figure out a different way so that we can set properties on devices without manually "guessing" the path. The idea is that the populate script would tell the caller where it put the devices, so that in the test code we would just use those paths -- it doesn't eliminate all the extra work, but at least we know for sure where the files are that we need to write to.

**Comment by ddemidov** [comment]
I wonder if adding a special property `device_path` (in a way, similar to `device_index`) to our specification will solve this. It would return full path to the connected device, and we could use it in the tests.

**Comment by WasabiFan** [comment]
> I wonder if adding a special property  device_path  (in a way, similar to  device_index ) to our specification will solve this. 

I think it would solve the issue, but it worries me that we would be using the code being tested to make the tests work. If the logic in our code was wrong and it didn't actually connect to the right device, the tests would have no way to catch that; right? So we would then need the script return the device path that it created to be able to confirm that the new `device_path` property was functioning :wink:

So if we want our tests to be _totally foolproof_, this isn't a solution. But if we are willing to accept that it is possible for some bugs in the connection logic to go undetected, I think it would be fine.

**Comment by ddemidov** [comment]
Ok, I am convinced. Please open a PR for this :).
