### ISSUE TITLE
Error when running clean script: we never create the "arena" directory

### ISSUE THREAD

**Issue by WasabiFan** [ddemidov/ev3dev-lang-fake-sys#4]
I'm getting the following error when running the ~~populate~~ clean script:

```
> Error: FileNotFoundError: [WinError 3] The system cannot find the path specified: '<...>\\ev3dev-lang-js\\test\\fake-sys\\arena'
    ----- Python Traceback -----
    File "<...>\ev3dev-lang-js\test\fake-sys\clean_arena.py", line 11, in <module>
      clean_arena()
    File "<...>\ev3dev-lang-js\test\fake-sys\clean_arena.py", line 8, in clean_arena
      shutil.rmtree(os.path.join(root, 'arena'))
    File "D:\tools\Python35\lib\shutil.py", line 488, in rmtree
      return _rmtree_unsafe(path, onerror)
    File "D:\tools\Python35\lib\shutil.py", line 370, in _rmtree_unsafe
      onerror(os.listdir, path, sys.exc_info())
    File "D:\tools\Python35\lib\shutil.py", line 368, in _rmtree_unsafe
      names = os.listdir(path)
```

... So the script doesn't actually ever create the `arena` directory, and it looks like the tree copy function isn't willing to create it for us. Is the proper solution to just add a `mkdir`-equivalent before the copy?

**Comment by WasabiFan** [comment]
If the answer is yes, I can fix it in my PR with the other changes.

**Comment by ddemidov** [comment]
hmm, [shutil.copytree](https://github.com/ddemidov/ev3dev-lang-fake-sys/blob/master/populate_arena.py#L27) handles that for me.

Ok, the problem is that `clean_arena` fails when there is nothing to clean. I think wrapping [this line](https://github.com/ddemidov/ev3dev-lang-fake-sys/blob/master/clean_arena.py#L8) into a `try/except` block should help.

**Comment by WasabiFan** [comment]
Oh wow, I completely missed the fact that it was running the clean script and not the populate one!

I'll make that change in my PR.

**Comment by ddemidov** [comment]
Even better, `rmtree` has `ignore_errors` flag: https://docs.python.org/2/library/shutil.html#shutil.rmtree
